language : python
python:
  - "2.6"
  - "2.7"

sudo: required

dist: trusty

install:
  - pip install -r requirements.txt

script: nosetests ./test

branches :
   only :
     - master
     - dev

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications :
   email :
     - maxwunj@gmail.com
