language : python
python:
  - "2.6"
  - "2.7"
  - "3.4"
  - "3.5"

sudo: required

dist: trusty

install:
  - pip install -r requirements.txt

script: nosetests -s -v --with-xunit --xunit-file circlestat_nose_xunit.xml --with-coverage --cover-package=me.maxwu --cover-html ./test
# -v -s --with-xunit --xunit-file XXXX_nose_xunit.xml --with-coverage --cover-package=cafe --cover-html --with-html

branches :
   only :
     - master
     - dev

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications :
   email :
     - maxwunj@gmail.com
